language: android

jdk:
  - oraclejdk8

env:
  global:
    - secure: "Ge+jCpENJt7ppa6zs3BJgK2hEPAlNZQTg0RwhOFZZXA5lxeNNe5vJF+aaZax95B1lHV7pW2hoeQosB7dWRvIo4pjxKR4e+etgVoGCWOt0a1sLatI9g+gm5oVGu3GZ7E5BHqkpaVQ7if5H0Lcg3tlCzTlhGKkZjZPQCUQsovFf00="
    - secure: "OVfIL3ggaGcDgJJhdWxYTCo3u38SNPNUNPsv6adHp5wW0Y2n1CF1zcAnZXhTkGEjoGvi0RuV8ZLG9jbmQdqxd17qBeBf2XPWKxyG1SUfegDVSy9OPF8BY11Fsp9I5RP1W3T/c32KTc7zvhtAivq9mbcrBYJZhDCKpZkdTNliFQ0="
    - GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  # $GPG_PASS is not defined for forks, so just skip it.
  - if [ -n "$GPG_PASS" ]; then echo $GPG_PASS | gpg --passphrase-fd 0 local.properties.gpg; fi
  - if [ -n "$GPG_PASS" ]; then echo $GPG_PASS | gpg --passphrase-fd 0 settings/signing.properties.gpg; fi
  - if [ -n "$GPG_PASS" ]; then echo $GPG_PASS | gpg --passphrase-fd 0 settings/release.keystore.gpg; fi
  - if [ -n "$GPG_PASS" ]; then echo $GPG_PASS | gpg --passphrase-fd 0 settings/service_account.json.gpg; fi
  - if [ -z "$GPG_PASS"]; then touch local.properties; fi

after_success:
  - if [ -n "$GITHUB_API_KEY" ]; then .buildscript/deploy_alpha.sh; fi

script: "./gradlew check"

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a9870bec6049c7309e68
    on_success: change
    on_failure: always
