language: android

jdk:
  - oraclejdk8

env:
  global:
    - secure: "OVfIL3ggaGcDgJJhdWxYTCo3u38SNPNUNPsv6adHp5wW0Y2n1CF1zcAnZXhTkGEjoGvi0RuV8ZLG9jbmQdqxd17qBeBf2XPWKxyG1SUfegDVSy9OPF8BY11Fsp9I5RP1W3T/c32KTc7zvhtAivq9mbcrBYJZhDCKpZkdTNliFQ0="
    - GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - $ANDROID_TARGET
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-$ANDROID_TARGET

before_install:
  - if [ -n "$encrypted_49e3b92debd1_key" ]; then openssl aes-256-cbc -K $encrypted_49e3b92debd1_key -iv $encrypted_49e3b92debd1_iv -in secrets.enc -out secrets -d; fi
  - if [ -n "$encrypted_49e3b92debd1_key" ]; then tar xvf secrets >/dev/null; fi
  - if [ -z "$encrypted_49e3b92debd1_key" ]; then touch local.properties; fi

before_script:
  - GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"
  - echo no | android create avd --force -n test -t $ANDROID_TARGET  --abi armeabi-v7a --skin WXGA720
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 30
  - adb shell settings put global window_animation_scale 0
  - adb shell settings put global transition_animation_scale 0
  - adb shell settings put global animator_duration_scale 0
  - adb shell input keyevent 82

after_success:
  - if [ -n "$GITHUB_API_KEY" ]; then .buildscript/deploy_alpha.sh; fi

script: "./gradlew check connectedMockDebugAndroidTest"

env:
  global:
    - secure: "SBlXs4v/M3GD1tRaT6zmMXVpMCUaL/oNcSjGWdHgI56DO5NOmTBmDW5kJTT5y0u0U7aE1/Dq22iXPut8NLxWsEi/20xBq3bXQh9ngRkvOstNX7Y0LqnhKBtPixnMIx07xAjUPYCmunJakCT7Hr4fqZAGfUwA4a3ZzRa/KVeNx2A="
    - secure: "OVfIL3ggaGcDgJJhdWxYTCo3u38SNPNUNPsv6adHp5wW0Y2n1CF1zcAnZXhTkGEjoGvi0RuV8ZLG9jbmQdqxd17qBeBf2XPWKxyG1SUfegDVSy9OPF8BY11Fsp9I5RP1W3T/c32KTc7zvhtAivq9mbcrBYJZhDCKpZkdTNliFQ0="
    - ADB_INSTALL_TIMEOUT=8
    - GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"
  matrix:
    - ANDROID_TARGET=android-22
    - ANDROID_TARGET=android-24

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a9870bec6049c7309e68
    on_success: change
    on_failure: always
